name: Typescript frontend OpenAPIClient Generate

on:
  pull_request:
    paths:
      - "src/v1.json"
      - ".github/workflows/generate_frontend.yaml"
      - "package.json"
    types:
      - closed
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          repository: CharVstack/CharV-frontend

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - run: yarn install --frozen-lockfile --prefer-offline

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: CharVstack/CharV-frontend
          path: frontend

      - run: yarn install --forzen-lockfile --prefer-offline
        working-directory: ./frontend

      - name: Clean Directory
        run: rm -rf ./frontend/src/api-hooks/v1

      - name: Generate
        run: yarn generate:typescript:v1

      - name: Run Prettier
        run: yarn fix:prettier
        working-directory: ./frontend

      - name: Run ESLint
        run: yarn eslint --fix 'src/api-hooks/**/*.{js,jsx,ts,tsx}'
        working-directory: ./frontend

      - name: Check Diff
        run: sh -c '! git diff --exit-code'
        working-directory: ./frontend

      - name: Copy Schema
        run: cp ./src/v1.json ./frontend/src/openapi-spec/v1.json

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          path: frontend
          commit-message: auto generated from ${{ github.event.pull_request.html_url }}
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.html_url }}
          branch: feature/codegen
          branch-suffix: short-commit-hash
