name: Typescript frontend OpenAPIClient Generate

on:
  pull_request:
    branches: 
      - main 
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        repository: CharVstack/CharV-backend

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - run: yarn install --frozen-lockfile

    - uses: actions/checkout@v3
      with:
        token: ${{ steps.generate_token.outputs.token }}
        repository: CharVstack/CharV-frontend
        path: frontend
        
    - name: Generate
      run: yarn generate:typescript
    
    - uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ steps.generate_token.outputs.token }}
        path: frontend
        commit-message: auto generated from ${{ github.event.pull_request.html_url }}
        title: ${{ github.event.pull_request.title }}
        body: ${{ github.event.pull_request.html_url }}
        branch: feature/codegen
        branch-suffix: short-commit-hash
